name: Bug Report
description: report a bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report.
        Please complete the following form to ask us for help with your issue.
  - type: textarea
    id: title
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Which steps should someone take to run into the same error?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs, tracebacks, messages, etc.
      description: Please copy-paste any relevant logs and/or error messages.
      render: shell
