name: Pylint

on:
  workflow_dispatch:  # Trigger the workflow manually
# on:
#   push:
#     branches:
#       - "main"
#   pull_request:
#     branches:
#       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pylint dependency
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Install package dependencies from pull request branch
      run: |
        cd package 
        python setup.py install 
      
    - name: Install promptflow dependencies
      run: | 
        python -m pip install promptflow
        python -m pip install promptflow-tools

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')