name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.pull_request.head.sha }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Create .env file in package directory 
        run: |
          cd package
          echo "COSMOS_DB_MONGO_URI = ${{ secrets.COSMOS_DB_MONGO_URI }}" >> /.env
          echo "DB_NAME =${{ secrets.DB_NAME }}" >> /.env
          echo "COLLECTION_NAME = ${{ secrets.COLLECTION_NAME }}" >> /.env
          echo "COSMOSDB_POSTGRES_CONN_STRING = $ {{ secrets.COSMOSDB_POSTGRES_CONN_STRING }}" >> /.env
          echo "TABLE_NAME = $ {{ secrets.TABLE_NAME }}" >> ./env

      - name: Install dependencies from pull request branch
        run: |
          python -m pip install --upgrade pip 
          cd package 
          python setup.py install 

      - name: Install pytest
        run: |
          python -m pip install pytest 

      - name: Run tests with installed dependancies 
        run: |
          cd package 
          pytest tests/ 